mineral_catalog/mineral/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.mineralsList, name='mineral_list'),
    url(r'^random/$', views.randomMineral, name='random_mineral'),
    url(r'^(?P<name>.*)/$', views.mineralDetail, name='mineral_detail'),
]

mineral_catalog/mineral_catalog/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views, settings

urlpatterns = [
    url(r'minerals/', include(('mineral.urls', 'minerals'), namespace='minerals')),
    url(r'admin/', admin.site.urls),
    url(r'^$', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns() 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mineral_catalog/mineral/models.py
from django.db import models


# Create your models here.

class Mineral(models.Model):
    name = models.CharField(max_length=255, unique=True, blank=True)
    image_filename = models.ImageField(upload_to='img', blank=True)
    image_caption = models.TextField(blank=True)
    category = models.CharField(max_length=255, blank=True)
    formula = models.TextField(blank=True)
    strunz_classification = models.TextField(blank=True)
    color = models.CharField(max_length=255, blank=True)
    crystal_system = models.CharField(max_length=255, blank=True)
    unit_cell = models.TextField(blank=True)
    crystal_symmetry = models.TextField(blank=True)
    cleavage = models.TextField(blank=True)
    mohs_scale_hardness = models.TextField(blank=True)
    luster = models.TextField(blank=True)
    streak = models.CharField(max_length=255, blank=True)
    diaphaneity = models.CharField(max_length=255, blank=True)
    optical_properties = models.TextField(blank=True)
    refractive_index = models.TextField(blank=True)
    crystal_habit = models.TextField(blank=True)
    specific_gravity = models.TextField(blank=True)
    group = models.CharField(max_length=255, blank=True)


    def __str__(self):
        return self.name

mineral_catalog/mineral/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import render
from .models import Mineral
from django.db import IntegrityError
from django.db import models
from mineral.utility import Utility

import json
import random


def mineralsList(request):
    minerals = Mineral.objects.all()
    return render(request, "mineral/minerals_list.html", {"minerals" : minerals})


def mineralDetail(request, name):
    mineral = get_object_or_404(Mineral, name=name)
    return render(request, "mineral/mineral_detail.html", {"mineral" : mineral})


def randomMineral(request):
    minerals = Mineral.objects.all()
    mineral = random.choice(minerals)
    return render(request, "mineral/random_mineral.html", {"mineral" : mineral})

mineral_catalog/mineral_catalog/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, "home.html")

mineral_catalog/mineral/templates/mineral/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %} | Macky's Minerals: A magnificant catalog of minerals</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
  </head>
  
  {% block content %}

  {% endblock %}

  <footer>
      <div class="minerals__random">
          <a class="minerals__anchor" href="{% url 'minerals:random_mineral' %}">Show random mineral</a>
      </div>
  </footer>
</html>

mineral_catalog/mineral/templates/mineral/mineral_detail.html
{% extends 'mineral/layout.html' %}
{% load static from staticfiles %}

{% block title %} 
    {{ mineral.name }}
{% endblock %}

{% block content %}
<body>
    <div class="bounds bounds--small">
        <div class="grid-100">
            <a href="{% url 'minerals:mineral_list' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>

        <div class="grid-100 mineral__container">
            <h1 class="mineral__name">{{ mineral.name }}</h1>
            <div class="mineral__image-bg">
                <img class="mineral__image" src="{{ mineral.image_filename.url }}">
                <p class="mineral__caption">{{ mineral.image_caption }}</p>
            </div>

            <div class="mineral__table-container">
                <table class="mineral__table">

                    {% if mineral.category %}
                        <tr>
                            <td class="mineral__category">Category</td>
                            <td>{{ mineral.category }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.formula %}
                        <tr>
                            <td class="mineral__category">Formula</td>
                            <td class="mineral__formula">{{ mineral.formula|safe }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.strunz_classification %}
                        <tr>
                            <td class="mineral__category">Strunz Classification</td>
                            <td>{{ mineral.strunz_classification }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.color %}
                        <tr>
                            <td class="mineral__category">Color</td>
                            <td>{{ mineral.color }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.crystal_system %}
                        <tr>
                            <td class="mineral__category">Crystal System</td>
                            <td>{{ mineral.crystal_system }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.unit_cell %}
                        <tr>
                            <td class="mineral__category">Unit Cell</td>
                            <td>{{ mineral.unit_cell }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.crystal_symmetry %}
                        <tr>
                            <td class="mineral__category">Crystal Symmetry</td>
                            <td>{{ mineral.crystal_symmetry }}</td>
                        </tr>
                    {% endif %}    
                    {% if mineral.cleavage %}
                        <tr>
                            <td class="mineral__category">Cleavage</td>
                            <td>{{ mineral.cleavage }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.mohs_scale_hardness %}
                        <tr>
                            <td class="mineral__category">Mohs Scale Hardness</td>
                            <td>{{ mineral.mohs_scale_hardness }}</td>
                        </tr>
                    {% endif %}   
                    {% if mineral.luster %}
                        <tr>
                            <td class="mineral__category">Luster</td>
                            <td>{{ mineral.luster }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.streak %}
                        <tr>
                            <td class="mineral__category">Streak</td>
                            <td>{{ mineral.streak }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.diaphaneity %}
                        <tr>
                            <td class="mineral__category">Diaphaneity</td>
                            <td>{{ mineral.diaphaneity }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.optical_properties %}
                        <tr>
                            <td class="mineral__category">Optical Properties</td>
                            <td>{{ mineral.optical_properties }}</td>
                        </tr>
                    {% endif %}      
                    {% if mineral.refractive_index %}
                        <tr>
                            <td class="mineral__category">Refractive Index</td>
                            <td>{{ mineral.refractive_index }}</td>
                        </tr>
                    {% endif %}                             
                    {% if mineral.crystal_habit %}
                        <tr>
                            <td class="mineral__category">Crystal Habit</td>
                            <td>{{ mineral.crystal_habit }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.specific_gravity %}
                        <tr>
                            <td class="mineral__category">Specific Gravity</td>
                            <td>{{ mineral.specific_gravity }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.group %}
                        <tr>
                            <td class="mineral__category">Group</td>
                            <td>{{ mineral.group }}</td>
                        </tr>
                    {% endif %}

                </table>
            </div>
        </div>
    </div>
</body>
{% endblock %}

mineral_catalog/mineral/templates/mineral/minerals_list.html
{% extends 'mineral/layout.html' %}
{% load static from staticfiles %}


{% block title %} Minerals List {% endblock %}


{% block content %}
<body>
    <div class="bounds">
        <div class="grid-100">
            <a href="{% url 'home' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                    <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                    <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                    <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>

        <div class="grid-100">
            <ul class="minerals__container">
                {% for mineral in minerals %}
                    <li class="minerals__item">
                        <a class="minerals__anchor" 
                            href="{% url 'minerals:mineral_detail' name=mineral.name %}">{{ mineral.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
{% endblock %}

mineral_catalog/mineral/templates/mineral/random_mineral.html
{% extends 'mineral/layout.html' %}
{% load static from staticfiles %}

{% block title %} 
    {{ mineral.name }}
{% endblock %}

{% block content %}
<body>
    <div class="bounds bounds--small">
        <div class="grid-100">
            <a href="{% url 'minerals:mineral_list' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
            </a>
            <p class="logo__text text-centered">They're not rocks!</p>
        </div>

        <div class="grid-100 mineral__container">
            <h1 class="mineral__name">{{ mineral.name }}</h1>
            <div class="mineral__image-bg">
                <img class="mineral__image" src="{{ mineral.image_filename.url }}">
                <p class="mineral__caption">{{ mineral.image_caption }}</p>
            </div>

            <div class="mineral__table-container">
                <table class="mineral__table">

                    {% if mineral.category %}
                        <tr>
                            <td class="mineral__category">Category</td>
                            <td>{{ mineral.category }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.formula %}
                        <tr>
                            <td class="mineral__category">Formula</td>
                            <td class="mineral__formula">{{ mineral.formula|safe }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.strunz_classification %}
                        <tr>
                            <td class="mineral__category">Strunz Classification</td>
                            <td>{{ mineral.strunz_classification }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.color %}
                        <tr>
                            <td class="mineral__category">Color</td>
                            <td>{{ mineral.color }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.crystal_system %}
                        <tr>
                            <td class="mineral__category">Crystal System</td>
                            <td>{{ mineral.crystal_system }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.unit_cell %}
                        <tr>
                            <td class="mineral__category">Unit Cell</td>
                            <td>{{ mineral.unit_cell }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.crystal_symmetry %}
                        <tr>
                            <td class="mineral__category">Crystal Symmetry</td>
                            <td>{{ mineral.crystal_symmetry }}</td>
                        </tr>
                    {% endif %}    
                    {% if mineral.cleavage %}
                        <tr>
                            <td class="mineral__category">Cleavage</td>
                            <td>{{ mineral.cleavage }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.mohs_scale_hardness %}
                        <tr>
                            <td class="mineral__category">Mohs Scale Hardness</td>
                            <td>{{ mineral.mohs_scale_hardness }}</td>
                        </tr>
                    {% endif %}   
                    {% if mineral.luster %}
                        <tr>
                            <td class="mineral__category">Luster</td>
                            <td>{{ mineral.luster }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.streak %}
                        <tr>
                            <td class="mineral__category">Streak</td>
                            <td>{{ mineral.streak }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.diaphaneity %}
                        <tr>
                            <td class="mineral__category">Diaphaneity</td>
                            <td>{{ mineral.diaphaneity }}</td>
                        </tr>
                    {% endif %} 
                    {% if mineral.optical_properties %}
                        <tr>
                            <td class="mineral__category">Optical Properties</td>
                            <td>{{ mineral.optical_properties }}</td>
                        </tr>
                    {% endif %}      
                    {% if mineral.refractive_index %}
                        <tr>
                            <td class="mineral__category">Refractive Index</td>
                            <td>{{ mineral.refractive_index }}</td>
                        </tr>
                    {% endif %}                             
                    {% if mineral.crystal_habit %}
                        <tr>
                            <td class="mineral__category">Crystal Habit</td>
                            <td>{{ mineral.crystal_habit }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.specific_gravity %}
                        <tr>
                            <td class="mineral__category">Specific Gravity</td>
                            <td>{{ mineral.specific_gravity }}</td>
                        </tr>
                    {% endif %}
                    {% if mineral.group %}
                        <tr>
                            <td class="mineral__category">Group</td>
                            <td>{{ mineral.group }}</td>
                        </tr>
                    {% endif %}

                </table>
            </div>
        </div>
    </div>
</body>
{% endblock %}

mineral_catalog/templates/home.html
{% extends 'mineral/layout.html' %}
{% load static from staticfiles %}

{% block title %} Welcome {% endblock %}

{% block content %}
<div class="bounds">
    <div class="grid-100">
        <a href="{% url 'minerals:mineral_list' %}">
            <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
            <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
            <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
            <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
            </svg>
            <h1 class="logo__name text-centered">Welcome to the<br>Macky's Minerals<br>Collection</h1>
        </a>
        <p class="logo__text text-centered">They're not rocks!</p>
    </div>
</div>
{% endblock %}